name: Rails Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install sqlite3
      run: sudo apt install -y sqlite3 libsqlite3-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build gems
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    - name: Setop Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install JS dependencies
      run: yarn
      
    - name: Migrate database
      run: bundle exec rails db:migrate RAILS_ENV=test
    - name: Run rails tests
      run: bundle exec rails test
      
    - name: Debug github variables
      run: | 
            echo ${{ github.event }}
            echo ${{ github.event_name }}
            echo ${{ github.ref }}
    
    - name: Save ssh private key to file
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: echo "$SSHKEY" > privatekey
      env:
        SSHKEY: ${{ secrets.SSH_KEY }} 
    - name: Pull from alwaysdata
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: ssh -i privatekey ubrisson@ssh-ubrisson.alwaysdata.net "git pull"
      
      

