name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install sqlite3
      run: sudo apt install -y sqlite3 & sudo apt install -y libsqlite3-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Execute webpacker
      run: bundle exec rails webpacker:compile
    - name: Run tests
      run: rails test
